FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
    openstack-ironic-inspector \
    && yum clean all

    {% elif base_distro in ['opensuse', 'sles'] %}

RUN pip install ironic-discoverd

    {% endif %}
{% endif %}

{{ include_footer }}

USER ironic
