FROM {{ namespace }}/{{ image_prefix }}gnocchi-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        openstack-gnocchi-api \
        openstack-gnocchi-carbonara \
        openstack-gnocchi-indexer-sqlalchemy \
    && yum clean all

    {% elif base_distro in ['opensuse', 'sles'] %}

RUN echo 'ERROR: {{ install_type }} is unavailable for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{{ include_footer }}

USER gnocchi
