FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        tftp-server \
        syslinux-tftpboot \
    && yum clean all

{% elif base_distro in ['opensuse', 'sles'] %}

RUN echo 'ERROR: {{ install_type }} is unavailable for {{ base_distro }}' \
    && /bin/false

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        tftpd-hpa \
        syslinux-common \
        syslinux \
    && apt-get clean

{% endif %}

COPY tftp-map-file /map-file
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{{ include_footer }}
