FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% elif base_distro in ['opensuse', 'sles'] %}

RUN zypper -n install \
        openstack-neutron-dhcp-agent \
    && zypper clean -a

    {% if base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        neutron-dhcp-agent \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER neutron
