FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        ceph \
        ceph-radosgw \
        parted \
        hdparm \
    && yum clean all

{% elif base_distro in ['opensuse', 'sles'] %}

RUN zypper -n install \
        net-tools \
        ceph \
        ceph-radosgw \
        parted \
        hdparm \
    && zypper clean -a

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        ceph \
        radosgw \
        parted \
        hdparm \
    && apt-get clean

{% endif %}

RUN useradd --user-group ceph \
    && mkdir -p /home/ceph \
    && chown -R ceph: /home/ceph
