FROM {{ namespace }}/{{ image_prefix }}murano-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        murano-engine \
    && apt-get clean

    {% elif base_distro in ['opensuse', 'sles'] %}

RUN echo 'ERROR: {{ install_type }} is unavailable for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% endif %}

{{ include_footer }}

USER murano
