FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        openvswitch \
    && yum clean all

{% elif base_distro in ['opensuse', 'sles'] %}

# kmod-compat --force to override modprobe deletion
RUN zypper -n install --force \
        kmod-compat \
        openvswitch \
        openvswitch-switch \
    && zypper clean -a

RUN mkdir -p /etc/openvswitch \
    && ln -s /run/openvswitch /var/run/

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends openvswitch-switch \
    && apt-get clean

{% endif %}
