FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y openstack-trove-taskmanager \
  && yum clean all

    {% elif base_distro in ['opensuse', 'sles'] %}

RUN echo 'ERROR: {{ install_type }} is unavailable for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% endif %}

{{ include_footer }}

USER trove
