FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y openstack-trove-taskmanager \
  && yum clean all

    {% elif base_distro in ['opensuse', 'sles'] %}

RUN zypper -n install \
        openstack-trove-taskmanager \
    && zypper clean -a

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        trove-taskmanager \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER trove
