FROM {{ namespace }}/{{ image_prefix }}murano-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        murano-api \
    && apt-get clean

    {% elif base_distro in ['opensuse', 'sles'] %}

RUN echo 'ERROR: {{ install_type }} is unavailable for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_murano_extend_start
RUN chmod 755 /usr/local/bin/kolla_murano_extend_start

{{ include_footer }}

USER murano
