FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        MariaDB-Galera-server \
        MariaDB-client \
        rsync \
        galera \
        socat \
        hostname \
        percona-xtrabackup \
        pv \
        tar \
        expect \
    && rm -rf /var/lib/mysql/*

{% elif base_distro in ['opensuse', 'sles'] %}

# FIXME: create a stable repo for MariaDB and Percona XtraBackup
RUN zypper -n install --from MariaDB \
        MariaDB-Galera-server \
        MariaDB-client \
        rsync \
        galera \
        socat \
        net-tools \
        tar \
        expect \
    && rm -rf /var/lib/mysql/* \
    && zypper clean -a

RUN rpm -i http://software.alchemy.solutions/repo/SUSE/Products/Cloud/6/x86_64/libgcrypt11-1.5.4-2.14.1.x86_64.rpm \
    && curl http://software.alchemy.solutions/repo/SUSE/Products/Cloud/6/x86_64/percona-xtrabackup-2.3.3-Linux-x86_64.tar.gz | tar -xz --strip-components=1 -C /usr percona-xtrabackup-2.3.3-Linux-x86_64/bin

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        mariadb-galera-server \
        percona-xtrabackup \
        socat \
        expect \
    && apt-get clean \
    && rm -rf /var/lib/mysql/*

{% endif %}

COPY mariadb_sudoers /etc/sudoers.d/mariadb_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY security_reset.expect /usr/local/bin/kolla_security_reset
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 755 /usr/local/bin/kolla_security_reset \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/mariadb_sudoers \
    && usermod -a -G kolla mysql

{{ include_footer }}

USER mysql
