FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        MariaDB-Galera-server \
        MariaDB-client \
        rsync \
        galera \
        socat \
        hostname \
        percona-xtrabackup \
        pv \
        tar \
        expect \
    && rm -rf /var/lib/mysql/*

{% elif base_distro in ['opensuse', 'sles'] %}

RUN zypper -n install \
        mariadb_101 \
        mariadb_101-client \
        galera-3 \
        xtrabackup \
        rsync \
        socat \
        net-tools \
        tar \
        expect \
    && zypper clean -a

RUN mkdir -p /var/lib/mysql /var/run/mysql \
    && chown mysql: /var/lib/mysql /var/run/mysql

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        mariadb-galera-server \
        percona-xtrabackup \
        socat \
        expect \
    && apt-get clean \
    && rm -rf /var/lib/mysql/*

{% endif %}

COPY mariadb_sudoers /etc/sudoers.d/mariadb_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY security_reset.expect /usr/local/bin/kolla_security_reset
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 755 /usr/local/bin/kolla_security_reset \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/mariadb_sudoers \
    && usermod -a -G kolla mysql

{{ include_footer }}

USER mysql
