FROM {{ namespace }}/{{ image_prefix }}manila-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['opensuse', 'sles'] %}

RUN zypper -n install \
        openstack-manila-scheduler \
    && zypper clean -a

    {% endif %}
{% endif %}

{{ include_footer }}

USER manila
