FROM {{ namespace }}/{{ image_prefix }}manila-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['opensuse', 'sles'] %}

RUN zypper -n install \
        openstack-manila-api \
    && zypper clean -a

    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{{ include_footer }}

USER manila
