FROM {{ namespace }}/{{ image_prefix }}ceilometer-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        openstack-ceilometer-compute \
        python-ceilometerclient \
    && yum clean all

    {% elif base_distro in ['opensuse', 'sles'] %}

RUN zypper -n install -y openstack-ceilometer-agent-compute \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        ceilometer-agent-compute \
        python-ceilometerclient \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER ceilometer
